# Generated by Django 4.2.1 on 2023-08-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplikacijaZaSportskaOpremaApp', '0002_delete_korisnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produkt',
            name='productDesc',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='produkt',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
