# Generated by Django 4.2.1 on 2023-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplikacijaZaSportskaOpremaApp', '0003_produkt_price_produkt_productdesc_produkt_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
