# Generated by Django 4.2.1 on 2023-08-31 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApplikacijaZaSportskaOpremaApp', '0006_category_produkt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApplikacijaZaSportskaOpremaApp.category'),
            preserve_default=False,
        ),
    ]
