# Generated by Django 4.2.1 on 2023-08-31 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApplikacijaZaSportskaOpremaApp', '0007_alter_produkt_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplikacijaZaSportskaOpremaApp.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplikacijaZaSportskaOpremaApp.cartitem')),
                ('shoppingCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApplikacijaZaSportskaOpremaApp.shoppingcart')),
            ],
        ),
    ]
