# Generated by Django 4.2.1 on 2023-08-31 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplikacijaZaSportskaOpremaApp', '0008_cartitem_shoppingcart_shoppingcartcartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='quantity',
        ),
    ]
