# Generated by Django 4.2.1 on 2023-08-31 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ApplikacijaZaSportskaOpremaApp', '0009_remove_produkt_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcartcartitem',
            name='cartItem',
        ),
        migrations.RemoveField(
            model_name='shoppingcartcartitem',
            name='shoppingCart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.DeleteModel(
            name='ShoppingCartCartItem',
        ),
    ]
