# Generated by Django 4.2.1 on 2023-08-31 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplikacijaZaSportskaOpremaApp', '0012_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2023, 8, 31, 20, 56, 51, 923976)),
        ),
    ]
